### ISSUE TITLE
What about deleted posts?

### ISSUE THREAD

**Issue by ghost** [as-com/s2forums-search#8]
If this search engine somehow can detect deleted posts... The STs will be mad :stuck_out_tongue:

**Comment by as-com** [comment]
Currently, the indexing script completely skips over deleted posts. If a post is already inside the database, it is not touched.

However, once indexing is complete, the indexer should be able to capture posts before anyone gets a chance to edit or delete them.

**Comment by ghost** [comment]
Ohh, ok :stuck_out_tongue_closed_eyes:
